### ISSUE TITLE
Set up Project document

### ISSUE THREAD

**Issue by Eirik2020** [Eirik2020/Statistical-Approach-to-System-Identification-of-Electric-Actuators#7]
Set up the project document.

## Todo
- [x] Create a document
- [x] Write down goals and scope
- [x] Set up theory section
- [x] Set up a skeleton template for the project.
